name: Test Web

on:
  pull_request:
    branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.Js
        uses: actions/setup-node@v4
        with:
            node-version-file: '.nvmrc'
    
      - name: Install
        run: corepack enable && yarn install --immutable
    
      - name: Test
        run: yarn workspace @sourcebot/web test --run
    
